### PR TITLE
Fixing issue with mass editing of waybills

### PR DESCRIPTION
**Pull request by francoisfeugeas**
Implements mass-editing of waybills in the AdminExportChronopost controller.

### CODE REVIEW

**Comment by francoisfeugeas** [comment]
@Quetzacoalt91 ready for you consideration !
@Klemart3D as discussed, I fixed the translation of the email subject for you

**Comment by Quetzacoalt91** [comment]
Hi @francoisfeugeas,

Do not forget to update your config.xml file. :)

**Comment by francoisfeugeas** [comment]
Done ! Sorry those were not tracked in the local repo.

**Comment by Quetzacoalt91** [comment]
Hi @francoisfeugeas,

I have just tested the button "Édition de l'étiquette Chronopost" and I get a blank page (However with a HTTP code 200). Can you please check that nothing is wrong ? Thanks

**Comment by francoisfeugeas** [comment]
Hi @Quetzacoalt91 

I couldn't reproduct this behaviour on my installation... 
Can you check again ? What Chronopost account are you using ? 

Thank you

**Comment by Quetzacoalt91** [comment]
Just checked on another shop and the issue still occurs :/

I will you the credentials I use by mail.

**Comment by francoisfeugeas** [comment]
Hello @Quetzacoalt91 

Still another round of tests and no luck reproducing. Are you using Chrono Relais or Chrono 13 when testing ? Is this on the latest release of Prestashop or your latest build ?

Can you please send me the Pickup point or the adress you are using ? (by email if need be)

Thank you

**Comment by Quetzacoalt91** [comment]
I tried on the unstable and the latest release of PrestaShop and the problem occurs on both versions.
The carrier used was *Chronopost - Livraison express en point relais*, with the pickup point based in Saint Lazare (4002R - PICKUP STORE gare St Lazare).

**Comment by francoisfeugeas** [comment]
@Quetzacoalt91 ... still can't reproduce on a fresh install. Can you please uncomment lines 314 to 317 of postSkybill.php on your install and attach the dump please ?

**Comment by francoisfeugeas** [comment]
@Quetzacoalt91 I received your dump, thank you. I can see that the waybill is successfully generted by Chronopost's WS, so no problem there ... 

Does the the table ps_chrono_lt_history exist in your install ?

**Comment by Quetzacoalt91** [comment]
:scream: 

capture du 2015-10-14 16 51 13

**Comment by francoisfeugeas** [comment]
@Quetzacoalt91, you must be testing on another branch, see https://github.com/francoisfeugeas/chronopost/blob/2bf004c50a3f2ee19bc8b0b0ed4ae80442c5f92d/chronopost.php#L473 ?

**Comment by Quetzacoalt91** [comment]
Hi @francoisfeugeas,

It was the mail subject coming from the rejected PR ! I have just removed the line.
The PR has just been merged and should be available soon.

Best regards

**Pull request merged**
