### PR TITLE
Merge pull request #1 from PrestaShop/master

### PR DESCRIPTION
**Pull request by Klemart3D**
Update

### CODE REVIEW

**Comment by Klemart3D** [comment]
Add a way to translate subject of Chronopost's automatic email for tracking number + french translation

**Comment by Quetzacoalt91** [comment]
Hi @Klemart3D,

Thanks, your PR has just been merged and the changes will be release with the next version of the module.

Best regards

**Comment by francoisfeugeas** [comment]
Hi @Klemart3D @Quetzacoalt91 

This merge should be reverted. 
You cannot call $this->l() from a static function

Thank you

**Comment by Klemart3D** [comment]
Hi @francoisfeugeas @Quetzacoalt91 

I'm sorry for that. Is there no way to translate the mail subject ?

**Comment by Quetzacoalt91** [comment]
Hi @francoisfeugeas,

Do not worry, this PR has only been applied on the dev branch and has not been published on the shops.

**Comment by francoisfeugeas** [comment]
Yes I did see we were on the dev branch. How often do you merge this branch with master ?

Can you revert this merge ?

Cordialement 
François Feugeas 

Oxileo 


---- Thomas N a écrit ----

**Comment by Quetzacoalt91** [comment]
I merge it when a new version need to be published. With Chronopost, it depends on your PRs @francoisfeugeas.

I suggest to not revert this commit but fix it instead.
We can translate the mail title with `Mail::l(...)`, or get an instance of Chronopost by calling `Module::getInstanceByName('chronopost')` and then call the function `l(...)` ?

**Comment by francoisfeugeas** [comment]
OK @Quetzacoalt91 thank you. 
I'll issue a fix for this in #26 then.

**Pull request merged**
