### PR TITLE
LT readable by all

### PR DESCRIPTION
**Pull request by Klemart3D**
Change chmod of LT pdf files to be readable by group + others (changed 600 to 644)

### CODE REVIEW

**Comment by francoisfeugeas** [comment]
Hello @Klemart3D 

I'm not sure if this is an improvement... Can you tell me more about your motives please ?

**Comment by Klemart3D** [comment]
Hi @francoisfeugeas 
Usually, all files included in Prestashop are, at worth, in 644 chmod (readable for everybody), for example : files in "download" or "upload" folders or all files in "config" folder. I fix it because when I'm trying a backup of all my Prestashop directory, the only "permission denied" files I have, it's for LT from chronopost module. Don't merge it if you're not sure, but for me, with this fix, it's work like a charm !

**Comment by francoisfeugeas** [comment]
Thanks for the explanation ! I'll let @Quetzacoalt91 decide if this a good idea vis à vis Prestashop best practices

**Comment by Quetzacoalt91** [comment]
Yep, sounds good for me. The default permissions are 644 for files and 755 for directories.

This PR can be merged.

**Comment by Quetzacoalt91** [comment]
Hi,

The PR has just been merged on the dev branch, and will be available with the next version of the module.

Best regards

**Pull request merged**
